baseURL = "https://mtuomiko.github.io/"
languageCode = "en-us"
title = "Matti Tuomikoski"
theme = "anatole"

[params]
displayMode = "dark"
title = "Matti Tuomikoski"
author = "Matti Tuomikoski"
#description = "Something"
profilePicture = "images/profile.jpg"
favicon = "favicons/"
mainSections = []
customCss = ["css/custom.css"]
#copyright = "test"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/matti-tuomikoski-3034251b6"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/mtuomiko/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mtuom@iki.fi"

[menu]

  [[menu.main]]
  name = "About me"
  identifier = "about"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Experience"
  weight = 200
  identifier = "experience"
  url = "/experience/"

  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/documents/cv-matti_tuomikoski.pdf"
